### ISSUE TITLE
No data returned

### ISSUE THREAD

**Issue by shaveosphere** [MitchSS/MMM-Hue#1]
Hi, great idea for a module - just can't seem to get it to work at all, all I get is "No Data returned". Is there a password required to access the Hue Developer account?

**Comment by MitchSS** [comment]
Hi,

You'll need to register here - http://www.developers.meethue.com/user/register

Then you can follow the instructions to creating your access on the bridge here - http://www.developers.meethue.com/documentation/getting-started

Give me a shout if you need any pointers

**Comment by MitchSS** [comment]
Once you have created the account on meethue, you can follow the instructions to create the account on the bridge.
