### ISSUE TITLE
hide more than 1 group

### ISSUE THREAD

**Issue by smotx** [MitchSS/MMM-Hue#10]
Hi,

anyone know how to 'hide' more than one groups.

I want to hide hgrp + dimmer.

Thanks for help

**Comment by Hristov94** [comment]
Need this info too :(

**Comment by MitchSS** [comment]
Unfortunately, I don't have any Hue bulbs any more so I'm unable to test this.

The repo has been forked multiple times, so maybe someone has resolved this issue already.
