### ISSUE TITLE
lightsorgroups not working

### ISSUE THREAD

**Issue by ghost** [MitchSS/MMM-Hue#14]
Hi, if i change the lightsorgroups to "lights", it doesnt show the right values. It jsut shows everything is off. But if i change it to groups, then it works just fine.... do you have any idea why it doesnt work.

`	{
			module: 'MMM-Hue',
			position: 'top_left',
			config: {
				bridgeip: "192.168.2.155",
				userid: "MYID",
				lightsorgroups: "groups",
				refreshTime: 1 * 500
			}
		}`

**Comment by BeLommel** [comment]
Hi,
i have the same issue, 
showOnlyOn and lightsorgroups are not working.


My Config:
 {
   module: 'MMM-Hue',
   position: 'top_right',
    config: {
        showOnlyOn: true,
        lightsorgroups: "lights",
	bridgeip: "xxx.xxx.xxx.xxx",
		  	userid: "my user id",
	  		colour: true
		    }

**Comment by MitchSS** [comment]
Unfortunately, I don't have any Hue bulbs any more so I'm unable to test/resolve this.

The repo has been forked multiple times, so maybe someone has resolved this issue already.
