### ISSUE TITLE
Light Status not updating

### ISSUE THREAD

**Issue by ghost** [MitchSS/MMM-Hue#2]
Hey I just installed MMM-Hue and it is working just fine expect that it doesn't update when i turn the light off/on
So it always displays the same no matter if I turned the lights off meanwhile...

Can anybody help with this?

**Comment by ghost** [comment]
Never mind, fixed it myself :D
I just was to excited and never let the lights lit for more then 10 minutes ^^

**Comment by PatrickGlatz** [comment]
Hello @MitchSS ,

I am also interested in this question. Also with me it does not update the light status, even when giving a refreshTime of 1 * 1000. Also tested with the default 60 * 10000 but also no good result. Would you mind looking into this? Or can you give me a hint? That would be really great and I would really appreciate it.

Thanks a lot in advance
Patrick

**Comment by MitchSS** [comment]
Hi Patrick,

Apologies, I did not receive a notification for this issue as it has been closed.

I'll take a look at the module at some point this week and will feedback.

Thanks

**Comment by slametps** [comment]
in my implementation, refreshTime works flawlessly. I set to 15 seconds. I also add translation and new option. 
@MitchSS : please check my pull request.

**Comment by BLoodConstructions** [comment]
Couldn’t get I status change. My lights are only showing off or “x”.  I still have an user Id which I needed for Homebridge. Do I need a second one, do I have to pair the bridge? Couldn’t get that fixed.

**Comment by aro28** [comment]
Hi all,
Same for me. Light Status is not updating. Need to wait a long time.

**Comment by mumblebaj** [comment]
Hi.  I have set my refresh to 1000*15 and my lights status is not updating.  Can you please help?  My Config:
`{
                    module: 'MMM-Hue',
                    position: 'bottom_right',
                    config:{
                bridgeip: "10.0.0.3",
                        userid: "my user name",
                        refreshTime: 1000 * 5,
                        lightsorgroups: "lights",
                        showLabel: true,
                colour: true
            }
                },
`

Am I missing something?

**Comment by mumblebaj** [comment]
Ok.  I changed lightsorgroups to groups and it now works perfectly.  Thanks for a great app.
