### ISSUE TITLE
ShowOnlyOn Not Working

### ISSUE THREAD

**Issue by brandongomez** [MitchSS/MMM-Hue#5]
Great module! I tried to do `showOnlyOn: true` but it still lists all the groups with an x and the lights that are on. What am I doing wrong? I just want to see the lights that are on and not all the ones with the x's next to them. Thanks!

**Comment by jaysalvat** [comment]
Hello there. Thanks for the module.

Same here. showOnlyOn doesn't work for me.

      config: {
        bridgeip: "192.168.1.xx",
        userid: "xxx",
        colour: false,
        refreshTime: 1000 * 5,
        showOnlyOn: true,
        lightsorgroups: "lights",
        showLabel: false
      }

Any idea?

**Comment by BeLommel** [comment]
Hi there,
i have the same issues,
showOnlyOn: true,
lightsorgroups: "lights",

did not work.
:-(

**Comment by MitchSS** [comment]
Unfortunately, I don't have any Hue bulbs any more so I'm unable to test this.

The repo has been forked multiple times, so maybe someone has resolved this issue already.
