### ISSUE TITLE
Cannot hide multiple groups

### ISSUE THREAD

**Issue by agskaali** [MitchSS/MMM-Hue#6]
I cannot hide multiple groups.

I have in totalt 4 groups:
Stue
Living
QuickHue: Switch Lights
QuickHue: Switch Lights

now I manage to hide for example the QuickHue which shares the name, but I can't hide those as well as one more.

How do I fix this?

**Comment by Sizer009** [comment]
Did you figure it out??

**Comment by agskaali** [comment]
No..
